### PR TITLE
Handle lists of more than 2^32 triples

### PR DESCRIPTION
**Pull request by Arkanosis**
This is required but probably not enough to handle big datasets such
as Wikidata (4.65 B triples).

This should partially address issue #135.

### CODE REVIEW

**Comment by wouterbeek** [comment]
@Arkanosis Thank you for working on the important topic of scalability.

Can you rebase this against `develop-64` (the branch for 64-bit support)?

**Comment by v4ss4llo** [comment]
As far as I understand, HDT allows triples to be specified with any number of bits (to be defined in a HDT header), so my guess is that they used 32bits by default, and for larger datasets more work is needed to parse the header correctly and support an arbitrary number of bits.

**Comment by v4ss4llo** [comment]
The branch structure of this repository is really confusing...

**Comment by LaurensRietveld** [comment]
We've merged the develop-64 branch to our develop branch. Let me know if you have any other issues. I'm assuming we can close this PR

**Pull request closed without merging**
