### PR TITLE
FIXED: Avoid object slicing when catching exceptions.

### PR DESCRIPTION
**Pull request by wouterbeek**

### CODE REVIEW

**Comment by mielvds** [comment]
No benefit?

**Comment by wouterbeek** [comment]
@mielvds I was cleaning up my list of pull requests that had not been integrated for a long time.

**Comment by mielvds** [comment]
Are they still relevant?

**Comment by wouterbeek** [comment]
Well...  I think we lack people who can properly test these pull requests.  My changes/additions were truly minor anyway.

**Pull request closed without merging**
