### PR TITLE
Refactoring configure.ac

### PR DESCRIPTION
**Pull request by ptorrestr**
Hi,

I modified a bit `configure.ac` in order to take advantage of pkgconfig when finding dependencies. Now using the flag `--with-serd` will indicate to configure script to look for the library `serd-0` in the system. If Serd is installed in the standard directories, then it should be picked up immediately. When Serd is installed in non-standard directory, the flags `SERD_CFLAGS` and `SERD_LIBS` can be used, or defining `PKG_CONFIG_PATH` at building time and `LD_LIBRARY_PATH` at runtime.

Also, I included a set of m4 macros to find the proper value for `-std` instead of adding it into `CXXFLAGS`.  If a compiler does not support C++11 features, then an error will be thrown during the configuration.  

Similarly, the optimisation parameters are by default included in the building. But, if an user wants to remove them, then he can use the flag `--disable-optimization`. This can help when including debugging symbols.

Finally, according to #96, Serd should be enable by default. If you agree with this I can include this feature in this PR.

### CODE REVIEW

**Comment by wouterbeek** [comment]
@ptorrestr Serd is already the default parser in the master branch.  In the development branch, building without Serd may not even be an option anymore, since this would result in an HDT build that cannot parse RDF data.

**Comment by LaurensRietveld** [comment]
You _could_ still query hdts. Not sure about others, but I'm always using hdt together with its parsing and serialization features, so I'm fine with listing it as required dep.

**Comment by LaurensRietveld** [comment]
Thanks @ptorrestr , works great!

**Comment by LaurensRietveld** [comment]
Ah, seems I tested serialization only. Parsing doesnt work though. Reason: `HAVE_SERD` does not seem to be set. Serialization still works, as there is a fallback built-in serializer. 
The configure command (without extra arguments) _does_ find the serd dep (`checking for SERD... yes
`. It seems somehow the `HAVE_SERD` still isnt set correctly. 

Given that serd is now a required dependency anyway, we could as well remove the `HAVE_SERD` checks

**Pull request merged**
