### PR TITLE
Allow for e.g., make OFLAGS="-O3 -fPIC" to compile for a shared object.

### PR DESCRIPTION
**Pull request by JanWielemaker**
The source needs to be compiled using -fPIC for embedding in a shared object.   Right now I do this using some `sed` magic, but that is needlessly complicated and causes the git submodule to be marked as dirty.  With this patch one can pass the desired options on the make command line easily.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
This might or might not cause trouble when compiling as a Node.js module; should be checked before merging.

**Comment by RubenVerborgh** [comment]
Falling build likely due to #66.

**Comment by JanWielemaker** [comment]
This shouldn't change anything, except when the Node.js integration is also hacking around the fixed Makefile.  I'd also be happy if the Makefile is renamed to e.g. Makefile.in and a configure script creates the Makefile or the user is simply asked to copy and edit the Makefile.

**Comment by RubenVerborgh** [comment]
I reset `develop` to the last working commit 7a067abde7be84a3ba4e74294bacb939b63767c7 and pushed the broken branch to `develop-broken`.

Could you rebase onto `develop`?

**Comment by RubenVerborgh** [comment]
Could you please rebase this on the latest develop?

**Comment by RubenVerborgh** [comment]
Presumed duplicate of #71.

**Pull request closed without merging**
