### PR TITLE
Make option

### PR DESCRIPTION
**Pull request by JanWielemaker**
Rebased to origin/develop as per request

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Could you please explain what this pull request does in the title and/or top comment?

Could you please rebase this on the latest develop?

**Comment by JanWielemaker** [comment]
I'm sorry, but I explained this patch more than good enough in my opinion and already rebased it once.  You can't ask people to keep working on a one line patch.   If you want to have it, simply make a branch, pull my pull request into it and to a `git cherry-pick <hash>` from your working branch.  If you don't, oh well.  I don't like the resulting dirty git repo, but I can live with it.

I'm doing a lot of integration as you may know and only ask people to rebase patches if they created them on a very old version and the rebase is not automatic and not obvious.

**Comment by wouterbeek** [comment]
@RubenVerborgh This pull request adds the `-fPIC` flag to the compilation steps in the Makefile ([changes](https://github.com/rdfhdt/hdt-cpp/pull/71/commits/906388a720847212ee94d2c45e275f3c5e0fec4a)).  It allows hdt-cpp to be reused from within another library.  E.g., we need it for the [HDT/Prolog API](https://github.com/JanWielemaker/hdt).  Currently we have to change the Makefile in some hacky while prior to building .  Jan has explained that this change does not break other ways in which the library is compiled/reused.  Specifically, it should not break the HDT/Node.js API.

@JanWielemaker The current situation is an exception because the development branch was broken for a long time (which explains why the process has been more cumbersome that it normally is).  We are of course very happy that Ruben stepped up to fix the development branch!

**Comment by RubenVerborgh** [comment]
Edited in as 604b844311d6faa745fdb5d67ae73f345981dc01, please verify and let me know.

**Pull request closed without merging**
