### PR TITLE
Fix conversion of serd nodes to strings

### LINKED ISSUE #59: Parsing of blank nodes
Parsing of blank nodes in the object position returns invalid terms. To reproduce:

`echo "<http://sub> <http://pred> _:b0." > test.nt &&  ./tools/rdf2hdt test.nt test.hdt && ./tools/hdtSearch -q '? ? ?' test.hdt 2>/dev/null`

HDT with the rapper parser returns `http://sub http://pred b0.` (notice the missing `_:`)
HDT with the serdi parser returns `http://sub http://pred _:b0.` (notice the trailing dot, which should not be there)

As a result, when you export this triple to RDF using `hdt2rdf`, you'll get invalid ntriples[1]

I'm confused about this issue though. Running `echo "<http://sub> <http://pred> _:b0." | serdi -` returns valid ntriples, i.e. serdi seems to parse/serialize this correctly.
But when I log the SerdNode value in the HDT serializer (https://github.com/rdfhdt/hdt-cpp/blob/develop/hdt-lib/src/rdf/RDFParserSerd.cpp#L18) I _do_ get the dot as part of the bnode value.

Some help is appreciated ;)

[1] 
serdi: `<http://sub> <http://pred> _:b0. .`
rapper: `<http://sub> <http://pred> <b0.> .`

### PR DESCRIPTION
**Pull request by drobilla**
Fixes #59

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
Thanks, could you clarify the necessity of this change? Did the Serd interface change?

**Comment by RubenVerborgh** [comment]
(I'm guessing there could be NULL chars in strings, which we would miss.)

**Comment by drobilla** [comment]
I believe it has always been this way, serd provides a length explicitly, not necessarily NULL termination, so if you assume NULL termination, bugs like #59 in the ttl/nt 1.1 grammar edge cases surrounding whitespace can result.  Converting with the given length is the better way regardless, even if serd can/did provide termination in these cases.

I'd have to check the grammar to see if NULL characters could actually be produced (since you can escape them, I imagine so), but yes, that's another reason, at least in theory.

**Comment by RubenVerborgh** [comment]
Makes sense, thanks!

**Comment by RubenVerborgh** [comment]
Build is broken though, but it already was before this commit.

**Comment by drobilla** [comment]
WFM.  Looks like CI needs to be updated to use serd from git, and possibly also has the wrong zlib version.

**Comment by drobilla** [comment]
I fixed the serd dep, but something is botched with zlib on Travis/Ubuntu.  No idea, it works with `zlib1g-dev` on stretch.

**Comment by RubenVerborgh** [comment]
The errors I see in the Travis logs. are unrelated to zlib.

@MarioAriasGa Could we please do something about the broken develop branch? I'll need to revert it to 2ca11fe0b448495f241cd85a06c170b4ae36b3fd otherwise, because we can no longer evaluate pull requests.

**Comment by RubenVerborgh** [comment]
I reset `develop` to the last working commit 7a067abde7be84a3ba4e74294bacb939b63767c7 and pushed the broken branch to `develop-broken`.

Could you try rebasing `serd-gzip` on `develop`?

**Comment by drobilla** [comment]
`gzbuffer` is a zlib function.

The others (pre GCC 6) are things being broken because of C++11 support as in the dev branch.

**Comment by drobilla** [comment]
Tried a build myself on Ubuntu 14.04.5 and it builds just fine.  I have no idea what is going on with the zlib on Travis.

**Comment by RubenVerborgh** [comment]
Can this be rebased on the latest develop, given #72?

**Comment by drobilla** [comment]
Done, but the Travis magic seems to be gone now...

**Comment by RubenVerborgh** [comment]
Weird, let me push this to a branch on this repo so we can get it to build.

**Comment by RubenVerborgh** [comment]
There we go.

**Comment by drobilla** [comment]
I'm guessing Travis has a libz that is over 7 years old.  Somehow.

Push that last commit and it possibly maybe might build.

**Comment by drobilla** [comment]
🎉

**Pull request merged**
