### PR TITLE
removed all references and files of raptor

### PR DESCRIPTION
**Pull request by dinikolop**
In reference to the issue #77

### CODE REVIEW

**Comment by LaurensRietveld** [comment]
Thanks dimitris! There are a few references to raptor left though (causing travis to fail). Could you remove those as well?

**Comment by LaurensRietveld** [comment]
@RubenVerborgh @webdata  got any experience with such failing travis tests? Cannot reproduce the failing tests locally (on a clean install of linux)

**Comment by RubenVerborgh** [comment]
I see `cannot find -lcds` in the logs, is it a path problem somehow?

**Comment by webdata** [comment]
It is compiling in my local linux as well (but I don't have travis locally installed, a problem in the paths of travis?)

**Comment by LaurensRietveld** [comment]
Yes, we noticed the missing cds dep as well. Couldn't figure out why though, largely because of failure to reproduce this locally. What kind of paths issues are you both thinking about?

**Comment by RubenVerborgh** [comment]
Can't tell… I suggest to either add more logging, or to fire up the Travis docker image to you have the exact same setup.

**Comment by LaurensRietveld** [comment]
Which docker image do you usually use for travis? (afaik there is no travis docker image for c++) Otherwise, we indeed have to resort to logging

**Comment by RubenVerborgh** [comment]
This might help: https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e

**Comment by LaurensRietveld** [comment]
It uses travis-jvm. As said, there doesnt seem to be a travis c++ container

**Comment by RubenVerborgh** [comment]
Hmm, there must be somewhere. Anything in the log about the worker that can help you out? https://travis-ci.org/rdfhdt/hdt-cpp/jobs/279926712#L1

**Comment by RubenVerborgh** [comment]
If not, there's always https://docs.travis-ci.com/user/running-build-in-debug-mode/ (haven't done this myself yet).

**Comment by LaurensRietveld** [comment]
ha, debug mode might help indeed. I'll try to get that enabled

**Comment by LaurensRietveld** [comment]
Debug mode was useful, the test-suite log reported:

<details>

FAIL: bit375


/home/travis/build/LaurensRietveld/hdt-cpp/libhdt/tests/.libs/lt-bit375: error while loading shared libraries: libserd-0.so.0: cannot open shared object file: No such file or directory

FAIL: logarr


/home/travis/build/LaurensRietveld/hdt-cpp/libhdt/tests/.libs/lt-logarr: error while loading shared libraries: libserd-0.so.0: cannot open shared object file: No such file or directory

FAIL: streamtest


/home/travis/build/LaurensRietveld/hdt-cpp/libhdt/tests/.libs/lt-streamtest: error while loading shared libraries: libserd-0.so.0: cannot open shared object file: No such file or directory

</details>

So serd does not seem to be properly included. 
This does not seem to be an issue directly introduced by this PR, as develop has the same issue (removing `--with-raptor2-prefix` from the develop travis build, make that one fail as well). 

I'm not sure why raptor is succesfully referenced by autotools, where serd isn't. Do you have an idea @drobilla ?

**Comment by RubenVerborgh** [comment]
Following up in https://github.com/rdfhdt/hdt-cpp/issues/97

**Comment by LaurensRietveld** [comment]
continued in #98

**Pull request closed without merging**
