### PR TITLE
Add method to directly load triples into BasicHDT

### PR DESCRIPTION
**Pull request by rubensworks**
This allows triples to be directly loaded into a BasicHDT without having to read them from a file.

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
@mielvds @joachimvh @laurensdv This is just what we needed for the management server. Now we can set up a pipeline unzip / clean / etc. without having to materialize.

**Comment by RubenVerborgh** [comment]
@LaurensRietveld @wouterbeek You will also like this; support for piping will likely simplify the LOD Laundromat internal pipeline.

**Comment by LaurensRietveld** [comment]
Cool stuff Ruben, thanks. This will indeed simplify some parts in our pipeline.
To verify: this PR means piped inputs, but not streamed HDT generation right? I.e., this does not affect the hardware footprint of the HDT generation process?

**Comment by rubensworks** [comment]
@LaurensRietveld Correct, it works the same way as generating HDT's from an input file, with the difference that this new method accepts a triple iterator instead of a file.

**Comment by mielvds** [comment]
Before I merge, what is the overlap between the `loadTriples ` and `loadDictionary` methods? Could this be written shorter and cleaner?

**Comment by rubensworks** [comment]
@mielvds You're right, I could abstract some things. The only real difference is the `ProgressListener` parameter. I'll look into it.

**Comment by rubensworks** [comment]
@mielvds All overlapping code between the `loadTriples` and `loadDictionary` methods has been abstracted.

**Comment by mielvds** [comment]
@rubensworks I did an attempt at merging this with the current develop branch, but I can't make it compile. There seems to be an issue with the inline functions you declared:

     [HDT] Compiling src/hdt/BasicHDT.cpp
    src/hdt/BasicHDT.cpp:273:9: error: expected expression
        return [fileName, baseUri, notation](RDFCallback& loader) {
               ^
    src/hdt/BasicHDT.cpp:282:9: error: expected expression
        return [triples](RDFCallback& loader) {
               ^
    2 errors generated.

Could you have a look? Result is in https://github.com/rdfhdt/hdt-cpp/tree/rubensworks-feature-loadtriples-single

**Comment by rubensworks** [comment]
@mielvds Apparently the Makefile isn't using c++11, in which lambda support was introduced.

So either we add `-stdlib=libc++ -std=c++11` to the default Makefile flags, which should be supported on most machines nowadays. Or I rewrite this PR so it doesn't use lambda's.

**Comment by RubenVerborgh** [comment]
I'd say; try C++11, and if Travis takes it, it's good.

**Comment by mielvds** [comment]
If it doesn't break backwards compatibility, fine by me.

**Comment by RubenVerborgh** [comment]
We can probably remove the gzip dependency after this PR?

**Comment by RubenVerborgh** [comment]
Could you please rebase this on the latest develop?

**Comment by RubenVerborgh** [comment]
How does this compare to #47? (CC: @drobilla)

**Comment by RubenVerborgh** [comment]
@rubensworks Based on your comment https://github.com/rdfhdt/hdt-cpp/issues/77#issuecomment-331363088, how do we proceed with this one?

**Comment by rubensworks** [comment]
@RubenVerborgh As this PR *only* adds a new method for streaming triples into `BasicHDT`, STDIN streaming would have to be implemented on top of that.
[Piping can however already be done on Mac and Linux](https://github.com/rdfhdt/hdt-cpp/issues/47#issuecomment-293081709).

So I suggest closing this PR, unless someone would require this functionality for something else.

**Comment by RubenVerborgh** [comment]
Agree on closing, thanks!

**Comment by mielvds** [comment]
@rubensworks can I delete the branch?

**Comment by LaurensRietveld** [comment]
Or, should we rebase this branch on dev and reopen this pr? I've yet to see anybody to convert a gzipped ntriples file to hdt, despite what the Readme says. And, got the impression @rubensworks that this pr can be used to convert gzipped files to hdt, is that correct?

**Comment by LaurensRietveld** [comment]
Sorry, ignore my last message (context: https://github.com/rdfhdt/hdt-cpp/issues/47#issuecomment-355739206)

**Pull request closed without merging**
